version: '3'

services:

  # postgres:
  #   container_name: postgres
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: mydb
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - dbdata:/var/lib/postgresql/data  

  # /var/run/postgresql

  redis:
    container_name: "redis"
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  go_app:
    container_name: go_app
    build:
      context: .
    command: ./main
    environment:
      - REDIS_DB_URL=redis-db:6379
      - REDIS_DB_PASSWORD=pass
      - REDIS_DB=0
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

volumes:
  dbdata:
